adding:
  dependencies:
    module:
      - autoban
      - block
      - config
      - config_delete
      - config_inspector
      - config_split
      - csp
      - devel
      - encrypt
      - field_ui
      - help
      - key
      - login_history
      - purge_users
      - s3fs
      - seckit
      - smtp
      - typed_entity_ui
      - userprotect
      - views_ui
      - workflows
  permissions:
    - 'access devel information'
    - 'access help pages'
    - 'access purge confirmation form'
    - 'access purge setting page'
    - 'admin tfa settings'
    - 'administer account settings'
    - 'administer actions'
    - 'administer autoban'
    - 'administer blocks'
    - 'administer configuration split'
    - 'administer contact_message display'
    - 'administer contact_message fields'
    - 'administer contact_message form display'
    - 'administer content types'
    - 'administer csp configuration'
    - 'administer display modes'
    - 'administer encrypt'
    - 'administer filters'
    - 'administer key configuration overrides'
    - 'administer keys'
    - 'administer login history'
    - 'administer media'
    - 'administer media display'
    - 'administer media fields'
    - 'administer media form display'
    - 'administer media types'
    - 'administer modules'
    - 'administer node display'
    - 'administer node fields'
    - 'administer node form display'
    - 'administer permissions'
    - 'administer rules'
    - 'administer rules components'
    - 'administer rules reactions'
    - 'administer s3fs'
    - 'administer seckit'
    - 'administer smtp module'
    - 'administer software updates'
    - 'administer taxonomy_term display'
    - 'administer taxonomy_term fields'
    - 'administer taxonomy_term form display'
    - 'administer themes'
    - 'administer user display'
    - 'administer user fields'
    - 'administer user form display'
    - 'administer views'
    - 'administer workflows'
    - 'bypass rules access'
    - 'cancel account'
    - 'configure navigation layout'
    - 'delete configuration'
    - 'disable own tfa'
    - 'explore typed entity classes'
    - 'export configuration'
    - 'import configuration'
    - 'inspect configuration'
    - 'select account cancellation method'
    - 'setup own tfa'
    - 'switch users'
    - 'synchronize configuration'
    - userprotect.administer
removing: {  }
