#!/usr/bin/env bash

## Description: Main to pitch
## Usage: main-to-pitch

ddev snapshot --cleanup --name "main-current" -y

ddev dotenv set .ddev/.env \
  --digitalocean-app="$(ddev dotenv get .ddev/.env --digitalocean-app-pitch)"

# Required to fix error that the dump exists in /tmp, presumably by wiping out
# /tmp.
ddev restart
ddev snapshot --name "main-current"
git checkout pitch
ddev snapshot restore "pitch-current"
ddev composer install
