#!/usr/bin/env bash

## Description: Create a deployment on DigitalOcean App Platform
## Usage: do-deploy
## Example: ddev do-deploy

# @see https://docs.digitalocean.com/reference/doctl/reference/apps/create-deployment/

doctl --access-token $DIGITALOCEAN_TOKEN apps create-deployment $DIGITALOCEAN_APP --verbose "$@"
