#!/usr/bin/env bash

## Description: Run Rclone inside the web container
## Usage: rclone [flags] [args]
## Example: ddev rclone --version

# @see https://rclone.org/

# @see https://superuser.com/questions/270214/how-can-i-change-the-colors-of-my-xterm-using-ansi-escape-sequences
RED='\033[31m'
GREEN='\033[32m'
YELLOW='\033[33m'
BLUE='\033[34m'
MAGENTA='\033[35m'
CYAN='\033[36m'
RESET='\033[0m'

if [[ -z "${RCLONE_CONFIG_FILE}" ]]; then

  printf "🛑 ${RED}The \"RCLONE_CONFIG_FILE\" environment variable must be set to run this command!${RESET}\n" >&2

  exit 1

fi

rclone --config="$RCLONE_CONFIG_FILE" "$@"
