#!/usr/bin/env bash

## Description: Remove workspaces defined in composerDependencies & composerWorkspaces from package.json and yarn.lock.
## Usage: yarn-remove-workspaces

# @see https://superuser.com/questions/270214/how-can-i-change-the-colors-of-my-xterm-using-ansi-escape-sequences
RED='\033[31m'
GREEN='\033[32m'
YELLOW='\033[33m'
BLUE='\033[34m'
MAGENTA='\033[35m'
CYAN='\033[36m'
RESET='\033[0m'

DEPENDENCIES_KEY='composerDependencies'

WORKSPACES_KEY='composerWorkspaces'

HAS_DEPENDENCIES="$(jq 'has($dependenciesKey)' package.json \
  --arg dependenciesKey $DEPENDENCIES_KEY \
  --raw-output \
)"

HAS_WORKSPACES="$(jq 'has($workspacesKey)' package.json \
  --arg workspacesKey $WORKSPACES_KEY \
  --raw-output \
)"

if [[ $HAS_DEPENDENCIES == 'false' ]] && [[ $HAS_WORKSPACES == 'false' ]]; then

  printf "🛑 ${RED}Your package.json contains neither \"$DEPENDENCIES_KEY\" nor \"$WORKSPACES_KEY\".${RESET}\n" >&2

  exit 1

fi

if [[ $HAS_DEPENDENCIES == 'false' ]]; then

  printf "🛑 ${RED}Your package.json is missing \"$DEPENDENCIES_KEY\".${RESET}\n" >&2

  exit 1

fi

if [[ $HAS_WORKSPACES == 'false' ]]; then

  printf "🛑 ${RED}Your package.json is missing \"$WORKSPACES_KEY\".${RESET}\n" >&2

  exit 1

fi

DEPENDENCIES_TYPE="$(jq '.[$dependenciesKey] | type' package.json \
  --arg dependenciesKey $DEPENDENCIES_KEY \
  --raw-output \
)"

if [[ $DEPENDENCIES_TYPE != "object" ]]; then

  printf "🛑 ${RED}The \"$DEPENDENCIES_KEY\" in your package.json must be an object; found $DEPENDENCIES_TYPE instead.${RESET}\n" >&2

  exit 1

fi

WORKSPACES_TYPE="$(jq '.[$workspacesKey] | type' package.json \
  --arg workspacesKey $WORKSPACES_KEY \
  --raw-output \
)"

if [[ $WORKSPACES_TYPE != "array" ]]; then

  printf "🛑 ${RED}The \"$WORKSPACES_KEY\" in your package.json must be an array; found $WORKSPACES_TYPE instead.${RESET}\n" >&2

  exit 1

fi

# Keep a copy of the lockfile with workspaces if yarn.lock exists.
if [ -f yarn.lock ]; then

  cp -f yarn.lock yarn.with-workspaces.lock

fi

# jq can't read and write to the same file reliably, resulting in an empty file,
# so we have to use a temp file to work around this.
#
# @see https://github.com/jqlang/jq/issues/2152#issuecomment-653634999
cp -f package.json /tmp/package.temp.json

# This removes both dependencies and workspaces found in composerDependencies
# and composerWorkspaces, respectively, leaving any other dependencies and
# workspaces as-is.
#
# Note the use of the "//" alternative operator on both .dependencies
# and .workspaces to ensure this doesn't fail if one or both are not present.
# While it's unlikely .dependencies would be missing, .workspaces can often be
# entirely omitted.
#
# @see https://jqlang.org/manual/#alternative-operator
jq '.dependencies = ((.dependencies // {} | to_entries) - (.[$dependenciesKey] | to_entries) | from_entries) | .workspaces = (.workspaces // []) - .[$workspacesKey]' /tmp/package.temp.json \
  --arg dependenciesKey $DEPENDENCIES_KEY \
  --arg workspacesKey $WORKSPACES_KEY \
  > package.json

rm -f /tmp/package.temp.json

yarn install
