_core:
  default_config_hash: PlWtVQXY5oKYZqCMPXh6SPamXagn5BoZqgAI8EY9WsY
icon_base_uri: 'public://media-icons/generic'
iframe_domain: 'https://omnH78jsVnKWAPD3s68WajKvtwbWHvfz8XC.dreamhosters.com'
oembed_providers_url: 'https://oembed.com/providers.json'
standalone_url: true
